[package]
name = "ts-garbage-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.33.26"
swc_ecma_parser = "0.144.1"
swc_ecma_ast = "0.113.1"
swc_ecma_visit = "0.99.1"
path-clean = "1.0.1"
vfs = "0.12.0"

