#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npx nx affected --target types, format:write --uncommitted
npm run test

cargo run --bin ts-garbage-collector-package-generator
cargo test